keybind = all:ctrl+alt+h=new_split:right
keybind = all:ctrl+alt+v=new_split:down
keybind = all:ctrl+h=goto_split:left
keybind = all:ctrl+j=goto_split:down
keybind = all:ctrl+k=goto_split:up
keybind = all:ctrl+l=goto_split:right

