background-opacity = 0.6
background-blur = true

cursor-style-blink = false
cursor-style = block
shell-integration-features = no-cursor
#theme = "Banana Blueberry"
#theme = "Banana Blueberry"
#theme = "Gruvbox Dark"
#title = "Ghostty terminal"
